---
kind: Namespace
apiVersion: v1
metadata:
  name: boras-tech-challenge-2024

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: boras-tech-challenge-2024
  name: application
  labels:
    app: boras-tech-challenge-2024
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boras-tech-challenge-2024
  template:
    metadata:
      labels:
        app: boras-tech-challenge-2024
    spec:
      containers:
        - name: application
          image: docker.viskan.com/boras-tech-challenge-2024:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: postgresql://<workspace ID>:<api key>@eu-west-1.sql.xata.sh:5432/boras-tech-challenge-2024:main?sslmode=require
            - name: NEXTAUTH_SECRET
              value: ...
            - name: NEXTAUTH_URL
              value: 'https://levelup-borås.viskan.com'
            - name: GOOGLE_CLIENT_ID
              value: ...
            - name: GOOGLE_CLIENT_SECRET
              value: ...
            - name: FACEBOOK_CLIENT_ID
              value: ...
            - name: FACEBOOK_CLIENT_SECRET
              value: ...
            - name: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
              value: ...

---
kind: Service
apiVersion: v1
metadata:
  namespace: boras-tech-challenge-2024
  name: application
spec:
  selector:
    app: boras-tech-challenge-2024
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  namespace: boras-tech-challenge-2024
  name: application
  labels:
    app: boras-tech-challenge-2024
spec:
  secretName: application-certificate
  commonName: xn--levelup-bors-3cb.viskan.com
  dnsNames:
    - xn--levelup-bors-3cb.viskan.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: boras-tech-challenge-2024
  name: application
  labels:
    app: boras-tech-challenge-2024
  annotations:
    nginx.ingress.kubernetes.io/enable-modsecurity: "false"
spec:
  ingressClassName: external
  rules:
    - host: xn--levelup-bors-3cb.viskan.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: application
                port:
                  number: 3000
  tls:
    - secretName: application-certificate
      hosts:
        - xn--levelup-bors-3cb.viskan.com
