import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import MenuBar from "./menu-bar-test/_components/MenuBar";
import Header from "./_components/header";
import Header2 from "./_components/header2";
import Header3 from "./_components/test";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Header/>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <div className="absolute bottom-5 left-1/2 -translate-x-1/2 transform">
          <MenuBar />
        </div>
      </body>
    </html>
  );
}
